name: ts

on:
  push:
    branches: [main]
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn lint
      - run: yarn format-check
      - run: yarn test
      - run: yarn build
      - run: yarn package

      - if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 e2e-test\n<!-- tail -->`
            })

      - if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `<!-- head -->\n👋 e2e-test`
            })

      - name: Get branch name on comment
        uses: xt0rted/pull-request-comment-branch@29fe0354c01b30fb3de76f193ab33abf8fe5ddb0 #1.2.0
        id: comment-branch
        if: github.event_name == 'issue_comment'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get branch name
        id: branch
        run: |
          case "${{ github.event_name }}" in
            issue_comment )     branch=${{ steps.comment-branch.outputs.head_ref }} ;;
            workflow_dispatch ) branch=${GITHUB_REF#refs/heads/} ;;
            * )                 branch=${{ github.head_ref }} ;;
          esac
          echo "::set-output name=branch::${branch}"

      - name: Get PR Number ${{ steps.branch.outputs.branch }}
        id: find-pr
        uses: jwalton/gh-find-current-pr@e12d66bc9ecc4fdcde07b0f70a3cb68ce7e4d807 # v1.3.0
        with:
          sha: ${{ steps.branch.outputs.branch }}
          state: open

      - name: e2e-test ${{ steps.find-pr.outputs.pr }}
        uses: ./
        with:
          pull-request-number: ${{ steps.find-pr.outputs.pr }}
          ends-with: |
            <!-- tail -->
          starts-with: |
            <!-- head -->

  generate:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn format
      - run: yarn graphql-codegen
      - uses: int128/update-generated-files-action@v2
